version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sitecounter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12lkd9h2oeinw"
s3_prefix = "sitecounter"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
