AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'crc'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  #HelloWorldFunction:
  #  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #  Properties:
  #    CodeUri: crc-serverless/
  #    Handler: app.lambda_handler
  #    Runtime: python3.9
  #    Events:
  #      HelloWorld:
  #        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #        Properties:
  #          Path: /hello
  #          Method: get
  #crcServerlessFunction:
  #  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #  Properties:
  #    CodeUri: crc-sitecounter/
  #    Handler: app.lambda_handler
  #    Runtime: python3.9
  #    Policies: [AWSLambdaDynamoDBExecutionRole, AmazonDynamoDBFullAccess, AWSLambdaInvocation-DynamoDB]
  #    Events:
  #      SiteCounter:
  #        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #        Properties:
  #          Path: /johnkoenigninjasitecounter
  #          Method: get
  ProcessDynamoDBStream:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: AWSLambdaDynamoDBExecutionRole
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "johnkoenig-ninja-counter5"
      AttributeDefinitions: 
        - AttributeName: "site"
          AttributeType: S
      KeySchema: 
        - AttributeName: "site"
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #SiteCounterApi:
  #  Description: "API Gateway endpoint URL for Prod stage for Site Counter function"
  #  Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/johnkoenig_ninja_sitecounter/"
  #SiteCounterFunction:
  #  Description: "Site Counter Lambda Function ARN"
  #  Value: !GetAtt SiteCounterFunction.Arn
  #SiteCounterFunctionIamRole:
  #  Description: "Implicit IAM Role created for Site Counter function"
  #  Value: !GetAtt SiteCounterFunction.Arn
