AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crc

  Sample SAM Template for crc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SiteCounterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sitecounter/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        SiteCounter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /johnkoenig_ninja_sitecounter
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SiteCounterApi:
    Description: "API Gateway endpoint URL for Prod stage for Site Counter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/johnkoenig_ninja_sitecounter/"
  SiteCounterFunction:
    Description: "Site Counter Lambda Function ARN"
    Value: !GetAtt SiteCounterFunction.Arn
  SiteCounterFunctionIamRole:
    Description: "Implicit IAM Role created for Site Counter function"
    Value: !GetAtt SiteCounterFunction.Arn
